// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrefixFuzzyAndTimeFilterProto.proto

package com.huangshihe.ecommerce.ecommercehbase.proto;

public final class PrefixFuzzyAndTimeFilterProto {
  private PrefixFuzzyAndTimeFilterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PrefixFuzzyAndTimeFilterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 prefixFuzzyLength = 1;
    /**
     * <code>required int32 prefixFuzzyLength = 1;</code>
     */
    boolean hasPrefixFuzzyLength();
    /**
     * <code>required int32 prefixFuzzyLength = 1;</code>
     */
    int getPrefixFuzzyLength();

    // required int64 startTimeStamp = 2;
    /**
     * <code>required int64 startTimeStamp = 2;</code>
     */
    boolean hasStartTimeStamp();
    /**
     * <code>required int64 startTimeStamp = 2;</code>
     */
    long getStartTimeStamp();

    // required int64 stopTimeStamp = 3;
    /**
     * <code>required int64 stopTimeStamp = 3;</code>
     */
    boolean hasStopTimeStamp();
    /**
     * <code>required int64 stopTimeStamp = 3;</code>
     */
    long getStopTimeStamp();
  }
  /**
   * Protobuf type {@code proto.PrefixFuzzyAndTimeFilter}
   */
  public static final class PrefixFuzzyAndTimeFilter extends
      com.google.protobuf.GeneratedMessage
      implements PrefixFuzzyAndTimeFilterOrBuilder {
    // Use PrefixFuzzyAndTimeFilter.newBuilder() to construct.
    private PrefixFuzzyAndTimeFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PrefixFuzzyAndTimeFilter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PrefixFuzzyAndTimeFilter defaultInstance;
    public static PrefixFuzzyAndTimeFilter getDefaultInstance() {
      return defaultInstance;
    }

    public PrefixFuzzyAndTimeFilter getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PrefixFuzzyAndTimeFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              prefixFuzzyLength_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startTimeStamp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              stopTimeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.internal_static_proto_PrefixFuzzyAndTimeFilter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.internal_static_proto_PrefixFuzzyAndTimeFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.class, com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.Builder.class);
    }

    public static com.google.protobuf.Parser<PrefixFuzzyAndTimeFilter> PARSER =
        new com.google.protobuf.AbstractParser<PrefixFuzzyAndTimeFilter>() {
      public PrefixFuzzyAndTimeFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrefixFuzzyAndTimeFilter(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PrefixFuzzyAndTimeFilter> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 prefixFuzzyLength = 1;
    public static final int PREFIXFUZZYLENGTH_FIELD_NUMBER = 1;
    private int prefixFuzzyLength_;
    /**
     * <code>required int32 prefixFuzzyLength = 1;</code>
     */
    public boolean hasPrefixFuzzyLength() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 prefixFuzzyLength = 1;</code>
     */
    public int getPrefixFuzzyLength() {
      return prefixFuzzyLength_;
    }

    // required int64 startTimeStamp = 2;
    public static final int STARTTIMESTAMP_FIELD_NUMBER = 2;
    private long startTimeStamp_;
    /**
     * <code>required int64 startTimeStamp = 2;</code>
     */
    public boolean hasStartTimeStamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 startTimeStamp = 2;</code>
     */
    public long getStartTimeStamp() {
      return startTimeStamp_;
    }

    // required int64 stopTimeStamp = 3;
    public static final int STOPTIMESTAMP_FIELD_NUMBER = 3;
    private long stopTimeStamp_;
    /**
     * <code>required int64 stopTimeStamp = 3;</code>
     */
    public boolean hasStopTimeStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 stopTimeStamp = 3;</code>
     */
    public long getStopTimeStamp() {
      return stopTimeStamp_;
    }

    private void initFields() {
      prefixFuzzyLength_ = 0;
      startTimeStamp_ = 0L;
      stopTimeStamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPrefixFuzzyLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStopTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, prefixFuzzyLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, startTimeStamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, stopTimeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, prefixFuzzyLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTimeStamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, stopTimeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter)) {
        return super.equals(obj);
      }
      com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter other = (com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter) obj;

      boolean result = true;
      result = result && (hasPrefixFuzzyLength() == other.hasPrefixFuzzyLength());
      if (hasPrefixFuzzyLength()) {
        result = result && (getPrefixFuzzyLength()
            == other.getPrefixFuzzyLength());
      }
      result = result && (hasStartTimeStamp() == other.hasStartTimeStamp());
      if (hasStartTimeStamp()) {
        result = result && (getStartTimeStamp()
            == other.getStartTimeStamp());
      }
      result = result && (hasStopTimeStamp() == other.hasStopTimeStamp());
      if (hasStopTimeStamp()) {
        result = result && (getStopTimeStamp()
            == other.getStopTimeStamp());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPrefixFuzzyLength()) {
        hash = (37 * hash) + PREFIXFUZZYLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getPrefixFuzzyLength();
      }
      if (hasStartTimeStamp()) {
        hash = (37 * hash) + STARTTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStartTimeStamp());
      }
      if (hasStopTimeStamp()) {
        hash = (37 * hash) + STOPTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStopTimeStamp());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PrefixFuzzyAndTimeFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.internal_static_proto_PrefixFuzzyAndTimeFilter_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.internal_static_proto_PrefixFuzzyAndTimeFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.class, com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.Builder.class);
      }

      // Construct using com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        prefixFuzzyLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        startTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        stopTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.internal_static_proto_PrefixFuzzyAndTimeFilter_descriptor;
      }

      public com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter getDefaultInstanceForType() {
        return com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.getDefaultInstance();
      }

      public com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter build() {
        com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter buildPartial() {
        com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter result = new com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.prefixFuzzyLength_ = prefixFuzzyLength_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startTimeStamp_ = startTimeStamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stopTimeStamp_ = stopTimeStamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter) {
          return mergeFrom((com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter other) {
        if (other == com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter.getDefaultInstance()) return this;
        if (other.hasPrefixFuzzyLength()) {
          setPrefixFuzzyLength(other.getPrefixFuzzyLength());
        }
        if (other.hasStartTimeStamp()) {
          setStartTimeStamp(other.getStartTimeStamp());
        }
        if (other.hasStopTimeStamp()) {
          setStopTimeStamp(other.getStopTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPrefixFuzzyLength()) {
          
          return false;
        }
        if (!hasStartTimeStamp()) {
          
          return false;
        }
        if (!hasStopTimeStamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.huangshihe.ecommerce.ecommercehbase.proto.PrefixFuzzyAndTimeFilterProto.PrefixFuzzyAndTimeFilter) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 prefixFuzzyLength = 1;
      private int prefixFuzzyLength_ ;
      /**
       * <code>required int32 prefixFuzzyLength = 1;</code>
       */
      public boolean hasPrefixFuzzyLength() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 prefixFuzzyLength = 1;</code>
       */
      public int getPrefixFuzzyLength() {
        return prefixFuzzyLength_;
      }
      /**
       * <code>required int32 prefixFuzzyLength = 1;</code>
       */
      public Builder setPrefixFuzzyLength(int value) {
        bitField0_ |= 0x00000001;
        prefixFuzzyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 prefixFuzzyLength = 1;</code>
       */
      public Builder clearPrefixFuzzyLength() {
        bitField0_ = (bitField0_ & ~0x00000001);
        prefixFuzzyLength_ = 0;
        onChanged();
        return this;
      }

      // required int64 startTimeStamp = 2;
      private long startTimeStamp_ ;
      /**
       * <code>required int64 startTimeStamp = 2;</code>
       */
      public boolean hasStartTimeStamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 startTimeStamp = 2;</code>
       */
      public long getStartTimeStamp() {
        return startTimeStamp_;
      }
      /**
       * <code>required int64 startTimeStamp = 2;</code>
       */
      public Builder setStartTimeStamp(long value) {
        bitField0_ |= 0x00000002;
        startTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 startTimeStamp = 2;</code>
       */
      public Builder clearStartTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      // required int64 stopTimeStamp = 3;
      private long stopTimeStamp_ ;
      /**
       * <code>required int64 stopTimeStamp = 3;</code>
       */
      public boolean hasStopTimeStamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 stopTimeStamp = 3;</code>
       */
      public long getStopTimeStamp() {
        return stopTimeStamp_;
      }
      /**
       * <code>required int64 stopTimeStamp = 3;</code>
       */
      public Builder setStopTimeStamp(long value) {
        bitField0_ |= 0x00000004;
        stopTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 stopTimeStamp = 3;</code>
       */
      public Builder clearStopTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stopTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.PrefixFuzzyAndTimeFilter)
    }

    static {
      defaultInstance = new PrefixFuzzyAndTimeFilter(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.PrefixFuzzyAndTimeFilter)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PrefixFuzzyAndTimeFilter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PrefixFuzzyAndTimeFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#PrefixFuzzyAndTimeFilterProto.proto\022\005p" +
      "roto\"d\n\030PrefixFuzzyAndTimeFilter\022\031\n\021pref" +
      "ixFuzzyLength\030\001 \002(\005\022\026\n\016startTimeStamp\030\002 " +
      "\002(\003\022\025\n\rstopTimeStamp\030\003 \002(\003BV\n-com.huangs" +
      "hihe.ecommerce.ecommercehbase.protoB\035Pre" +
      "fixFuzzyAndTimeFilterProtoH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_PrefixFuzzyAndTimeFilter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_PrefixFuzzyAndTimeFilter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_PrefixFuzzyAndTimeFilter_descriptor,
              new java.lang.String[] { "PrefixFuzzyLength", "StartTimeStamp", "StopTimeStamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
